.TH "GameState::SingleplayerGameState" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameState::SingleplayerGameState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SingleplayerGameState\&.h>\fP
.PP
Inherits \fBGameState::AbstractGameState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleplayerGameState\fP (\fBViewModel::BaseViewModel\fP *\fBRenderingModel\fP)"
.br
.ti -1c
.RI "virtual \fBAbstractGameState\fP * \fBrun\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameState::SingleplayerGameState::SingleplayerGameState (\fBViewModel::BaseViewModel\fP * RenderingModel)"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBAbstractGameState\fP* GameState::SingleplayerGameState::run ()\fC [virtual]\fP"

.PP
Implements \fBGameState::AbstractGameState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
