.TH "GameState::SplashScreenGameState" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameState::SplashScreenGameState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SplashScreenGameState\&.h>\fP
.PP
Inherits \fBGameState::AbstractGameState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashScreenGameState\fP (\fBViewModel::BaseViewModel\fP *\fBRenderingModel\fP, \fBMenuGameState\fP *\fBNextState\fP)"
.br
.ti -1c
.RI "virtual \fBAbstractGameState\fP * \fBrun\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBMenuGameState\fP * \fBNextState\fP"
.br
.ti -1c
.RI "const uint32_t \fBSleepForSecond\fP = 1"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameState::SplashScreenGameState::SplashScreenGameState (\fBViewModel::BaseViewModel\fP * RenderingModel, \fBMenuGameState\fP * NextState)"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBAbstractGameState\fP* GameState::SplashScreenGameState::run ()\fC [virtual]\fP"

.PP
Implements \fBGameState::AbstractGameState\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMenuGameState\fP* GameState::SplashScreenGameState::NextState\fC [private]\fP"

.SS "const uint32_t GameState::SplashScreenGameState::SleepForSecond = 1\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
