.TH "valkopat/src/ViewModels/SDL/ScoreSDLViewModel.h" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
valkopat/src/ViewModels/SDL/ScoreSDLViewModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Abstract/ScoreAbstractViewModel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBViewModel::ScoreSDLViewModel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBViewModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
