.TH "ViewModel::MenuAbstractViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::MenuAbstractViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MenuAbstractViewModel\&.h>\fP
.PP
Inherited by \fBViewModel::MenuConsoleViewModel\fP, and \fBViewModel::MenuSDLViewModel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMenuEntry\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~MenuAbstractViewModel\fP ()"
.br
.ti -1c
.RI "virtual int \fBShowMenu\fP (std::vector< \fBMenuEntry\fP >)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ViewModel::MenuAbstractViewModel::~MenuAbstractViewModel ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual int ViewModel::MenuAbstractViewModel::ShowMenu (std::vector< \fBMenuEntry\fP >)\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::MenuConsoleViewModel\fP, and \fBViewModel::MenuSDLViewModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
