.TH "ViewModel::ViewModelChooser" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::ViewModelChooser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ViewModelChooser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseViewModel\fP * \fBChooseViewModel\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBBaseViewModel\fP * > \fBPrepareViewModels\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBBaseViewModel\fP* ViewModel::ViewModelChooser::ChooseViewModel ()"

.SS "std::vector<\fBBaseViewModel\fP*> ViewModel::ViewModelChooser::PrepareViewModels ()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
