.TH "ViewModel::ScoreNCursesViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::ScoreNCursesViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScoreNCursesViewModel\&.h>\fP
.PP
Inherits \fBViewModel::ScoreAbstractViewModel\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
