.TH "ViewModel::GameConsoleViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::GameConsoleViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameConsoleViewModel\&.h>\fP
.PP
Inherits \fBViewModel::GameAbstractViewModel\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
