.TH "ViewModel::NetMenuAbstractViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::NetMenuAbstractViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NetMenuAbstractViewModel\&.h>\fP
.PP
Inherited by \fBViewModel::NetMenuConsoleViewModel\fP, and \fBViewModel::NetMenuSDLViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~NetMenuAbstractViewModel\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ViewModel::NetMenuAbstractViewModel::~NetMenuAbstractViewModel ()\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
