.TH "ViewModel::LanguageConsoleViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::LanguageConsoleViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LanguageConsoleViewModel\&.h>\fP
.PP
Inherits \fBViewModel::LanguageAbstractViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBShowMenu\fP (std::vector< \fBLanguageEntry\fP >)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual int ViewModel::LanguageConsoleViewModel::ShowMenu (std::vector< \fBLanguageEntry\fP >)\fC [virtual]\fP"

.PP
Implements \fBViewModel::LanguageAbstractViewModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
