.TH "ViewModel::BaseViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::BaseViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseViewModel\&.h>\fP
.PP
Inherited by \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~BaseViewModel\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBGetNameofViewModel\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()=0"
.br
.ti -1c
.RI "virtual \fBSplashScreenAbstractViewModel\fP * \fBSplashScreenModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBMenuAbstractViewModel\fP * \fBMenuModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBLanguageAbstractViewModel\fP * \fBLanguageModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBMultiplayerMenuAbstractViewModel\fP * \fBMultiplayerModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBNetMenuAbstractViewModel\fP * \fBNetModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBSingleplayerMenuAbstractViewModel\fP * \fBSingleplayerModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBGameAbstractViewModel\fP * \fBGameModel\fP ()=0"
.br
.ti -1c
.RI "virtual \fBScoreAbstractViewModel\fP * \fBScoreModel\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ViewModel::BaseViewModel::~BaseViewModel ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBGameAbstractViewModel\fP* ViewModel::BaseViewModel::GameModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual const char* ViewModel::BaseViewModel::GetNameofViewModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual void ViewModel::BaseViewModel::init ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBLanguageAbstractViewModel\fP* ViewModel::BaseViewModel::LanguageModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBMenuAbstractViewModel\fP* ViewModel::BaseViewModel::MenuModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBMultiplayerMenuAbstractViewModel\fP* ViewModel::BaseViewModel::MultiplayerModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBNetMenuAbstractViewModel\fP* ViewModel::BaseViewModel::NetModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBScoreAbstractViewModel\fP* ViewModel::BaseViewModel::ScoreModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBSingleplayerMenuAbstractViewModel\fP* ViewModel::BaseViewModel::SingleplayerModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.
.SS "virtual \fBSplashScreenAbstractViewModel\fP* ViewModel::BaseViewModel::SplashScreenModel ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::ConsoleViewModel\fP, and \fBViewModel::SDLViewModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
