.TH "ViewModel::ConsoleViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::ConsoleViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConsoleViewModel\&.h>\fP
.PP
Inherits \fBViewModel::BaseViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ConsoleViewModel\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBGetNameofViewModel\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual \fBSplashScreenAbstractViewModel\fP * \fBSplashScreenModel\fP ()"
.br
.ti -1c
.RI "virtual \fBMenuAbstractViewModel\fP * \fBMenuModel\fP ()"
.br
.ti -1c
.RI "virtual \fBLanguageAbstractViewModel\fP * \fBLanguageModel\fP ()"
.br
.ti -1c
.RI "virtual \fBMultiplayerMenuAbstractViewModel\fP * \fBMultiplayerModel\fP ()"
.br
.ti -1c
.RI "virtual \fBNetMenuAbstractViewModel\fP * \fBNetModel\fP ()"
.br
.ti -1c
.RI "virtual \fBSingleplayerMenuAbstractViewModel\fP * \fBSingleplayerModel\fP ()"
.br
.ti -1c
.RI "virtual \fBGameAbstractViewModel\fP * \fBGameModel\fP ()"
.br
.ti -1c
.RI "virtual \fBScoreAbstractViewModel\fP * \fBScoreModel\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSplashScreenAbstractViewModel\fP * \fBSplashScren\fP"
.br
.ti -1c
.RI "\fBMenuAbstractViewModel\fP * \fBMenu\fP"
.br
.ti -1c
.RI "\fBLanguageAbstractViewModel\fP * \fBLanguage\fP"
.br
.ti -1c
.RI "\fBMultiplayerMenuAbstractViewModel\fP * \fBMultiplayer\fP"
.br
.ti -1c
.RI "\fBNetMenuAbstractViewModel\fP * \fBNetMenu\fP"
.br
.ti -1c
.RI "\fBSingleplayerMenuAbstractViewModel\fP * \fBSingpleplayer\fP"
.br
.ti -1c
.RI "\fBGameAbstractViewModel\fP * \fBGame\fP"
.br
.ti -1c
.RI "\fBScoreAbstractViewModel\fP * \fBScore\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ViewModel::ConsoleViewModel::~ConsoleViewModel ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBGameAbstractViewModel\fP* ViewModel::ConsoleViewModel::GameModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual const char* ViewModel::ConsoleViewModel::GetNameofViewModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual void ViewModel::ConsoleViewModel::init ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBLanguageAbstractViewModel\fP* ViewModel::ConsoleViewModel::LanguageModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::MenuModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBMultiplayerMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::MultiplayerModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBNetMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::NetModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBScoreAbstractViewModel\fP* ViewModel::ConsoleViewModel::ScoreModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBSingleplayerMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::SingleplayerModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBSplashScreenAbstractViewModel\fP* ViewModel::ConsoleViewModel::SplashScreenModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameAbstractViewModel\fP* ViewModel::ConsoleViewModel::Game\fC [private]\fP"

.SS "\fBLanguageAbstractViewModel\fP* ViewModel::ConsoleViewModel::Language\fC [private]\fP"

.SS "\fBMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::Menu\fC [private]\fP"

.SS "\fBMultiplayerMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::Multiplayer\fC [private]\fP"

.SS "\fBNetMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::NetMenu\fC [private]\fP"

.SS "\fBScoreAbstractViewModel\fP* ViewModel::ConsoleViewModel::Score\fC [private]\fP"

.SS "\fBSingleplayerMenuAbstractViewModel\fP* ViewModel::ConsoleViewModel::Singpleplayer\fC [private]\fP"

.SS "\fBSplashScreenAbstractViewModel\fP* ViewModel::ConsoleViewModel::SplashScren\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
