.TH "ViewModel::SplashScreenAbstractViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::SplashScreenAbstractViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SplashScreenAbstractViewModel\&.h>\fP
.PP
Inherited by \fBViewModel::SplashScreenConsoleViewModel\fP, and \fBViewModel::SplashScreenSDLViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SplashScreenAbstractViewModel\fP ()"
.br
.ti -1c
.RI "virtual void \fBShowSplashScreen\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ViewModel::SplashScreenAbstractViewModel::~SplashScreenAbstractViewModel ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void ViewModel::SplashScreenAbstractViewModel::ShowSplashScreen ()\fC [pure virtual]\fP"

.PP
Implemented in \fBViewModel::SplashScreenConsoleViewModel\fP, and \fBViewModel::SplashScreenSDLViewModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
