.TH "ViewModel::MenuSDLViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::MenuSDLViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MenuSDLViewModel\&.h>\fP
.PP
Inherits \fBViewModel::MenuAbstractViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBShowMenu\fP (std::vector< \fBMenuEntry\fP >)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual int ViewModel::MenuSDLViewModel::ShowMenu (std::vector< \fBMenuEntry\fP >)\fC [virtual]\fP"

.PP
Implements \fBViewModel::MenuAbstractViewModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
