.TH "ViewModel::NCursesViewModel" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::NCursesViewModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NCursesViewModel\&.h>\fP
.PP
Inherits \fBViewModel::BaseViewModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBGetNameofViewModel\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual \fBSplashScreenAbstractViewModel\fP * \fBSplashScreenModel\fP ()"
.br
.ti -1c
.RI "virtual \fBMenuAbstractViewModel\fP * \fBMenuModel\fP ()"
.br
.ti -1c
.RI "virtual \fBLanguageAbstractViewModel\fP * \fBLanguageModel\fP ()"
.br
.ti -1c
.RI "virtual \fBMultiplayerMenuAbstractViewModel\fP * \fBMultiplayerModel\fP ()"
.br
.ti -1c
.RI "virtual \fBNetMenuAbstractViewModel\fP * \fBNetModel\fP ()"
.br
.ti -1c
.RI "virtual \fBSingleplayerMenuAbstractViewModel\fP * \fBSingleplayerModel\fP ()"
.br
.ti -1c
.RI "virtual \fBGameAbstractViewModel\fP * \fBGameModel\fP ()"
.br
.ti -1c
.RI "virtual \fBScoreAbstractViewModel\fP * \fBScoreModel\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBGameAbstractViewModel\fP* ViewModel::NCursesViewModel::GameModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual const char* ViewModel::NCursesViewModel::GetNameofViewModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual void ViewModel::NCursesViewModel::init ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBLanguageAbstractViewModel\fP* ViewModel::NCursesViewModel::LanguageModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBMenuAbstractViewModel\fP* ViewModel::NCursesViewModel::MenuModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBMultiplayerMenuAbstractViewModel\fP* ViewModel::NCursesViewModel::MultiplayerModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBNetMenuAbstractViewModel\fP* ViewModel::NCursesViewModel::NetModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBScoreAbstractViewModel\fP* ViewModel::NCursesViewModel::ScoreModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBSingleplayerMenuAbstractViewModel\fP* ViewModel::NCursesViewModel::SingleplayerModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.
.SS "virtual \fBSplashScreenAbstractViewModel\fP* ViewModel::NCursesViewModel::SplashScreenModel ()\fC [virtual]\fP"

.PP
Implements \fBViewModel::BaseViewModel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
