.TH "ViewModel::MenuAbstractViewModel::MenuEntry" 3 "Mon Apr 11 2016" "Nibbles Semestral work" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModel::MenuAbstractViewModel::MenuEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MenuAbstractViewModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "std::string \fBText\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ViewModel::MenuAbstractViewModel::MenuEntry::index"

.SS "std::string ViewModel::MenuAbstractViewModel::MenuEntry::Text"


.SH "Author"
.PP 
Generated automatically by Doxygen for Nibbles Semestral work from the source code\&.
